### ISSUE TITLE
README producer and consumer examples have wrong serializer

### ISSUE THREAD

**Issue by paulparkinson** [oracle/okafka#1]
All "org.apache.kafka.common.serialization.StringSerializer" values should be "org.oracle.okafka.common.serialization.StringSerializer"

**Comment by pasimoes** [comment]
@paulparkinson, this issue may be closed. Could you please verify? PR #12 handled it.

**Comment by paulparkinson** [comment]
the change made in the PR is from 
org.apache.kafka 
to 
org.apache.okafka 
It should be 
org.oracle.okafka 
or alternatively 
org.oracle.kafka
